name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Diff Functions
        id: diff_functions
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            mjaisimulator/**/*.py
            tests/**/*.py

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter python3.10
          sccache: "true"
          manylinux: auto

      - name: Install wheel package
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black isort pyright pytest
          python -m pip install ./dist/mjaisimulator-*-cp310-*.whl

      - name: black
        run: black python tests --check --diff
      - name: flake8
        run: flake8 python tests
      - name: isort
        run: isort python tests --check --diff
      - name: pyright
        run: pyright python tests
